version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/taximanager?serverVersion=16&charset=utf8

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taximanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
